version: '3.8'

services:
  backend-core:
    image: backend-core:latest
    build:
      context: ./wf-core-services
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE": "${MARIADB_DATABASE}"

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER": "${MARIADB_USER}"
      MARIADB_DATABASE": "${MARIADB_DATABASE}"
    ports:
      - "3306:3306"