version: '3.8'

services:
  backend-core:
    image: backend-core:latest
    build:
      context: ./wf-core-services
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"

  backend-statistics:
    image: backend-statistics:latest
    build:
      context: ./wf-stats-services
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"

  db:
    image: mariadb:latest
    container_name: weather-fetcher-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER": "${MARIADB_USER}"
      MARIADB_PASSWORD": "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    ports:
      - "3306:3306"